defaults:
  - policy_training_wrapper_config: prediction_wrapper
  - data_curator_config: prediction
  - loss_config:
    - vae_loss_gmm_covar_prior
  - loss_config@additional_dev_loss_config:
    - posterior_minADE_loss
    - posterior_minFDE_loss
    - prior_minADE_loss
    - prior_minFDE_loss
    - NLL_configs/prior_mixture_NLL_at1s
    - NLL_configs/prior_mixture_NLL_at2s
    - NLL_configs/prior_mixture_NLL_at3s
    - NLL_configs/posterior_mixture_NLL_at1s
    - NLL_configs/posterior_mixture_NLL_at2s
    - NLL_configs/posterior_mixture_NLL_at3s
additional_train_loss_config: null
clip_grad_norm_to: 1.0
epochs: 40
evaluate_dev_loss_every_nth_epoch: 1
experiment_name: Debug
learning_rate: 0.0001
learning_rate_scheduler:
  path_to_class: torch.optim.lr_scheduler.MultiStepLR
  config:
    gamma: 0.5
    milestones: [ 19, 24, 29, 34 ]
    verbose: true
mlflow_directory: ???
mlflow_run_name: '-'
policy_directory: ???
use_gpu: true
weight_decay: 0.0
